# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.0.0-rc2


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
from sklearn.datasets import load_iris
iris = load_iris()

#from sklearn import datasets
#data = datasets.load_iris

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
#(trainX, trainY),(testX, testY) = tf.keras.datasets.load_iris.load_data()
X = iris.data
y = iris.target


## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split
#from sklearn.model_selection import StratifiedShuffleSplit
train_set, test_set, train_labels, test_labels = train_test_split(X, y, test_size=0.25, random_state=0)



In [85]:
train_set.shape

(112, 4)

In [86]:
train_labels[0]

1

In [87]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [37]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
train_labels = tf.keras.utils.to_categorical(train_labels, num_classes=3)
test_labels = tf.keras.utils.to_categorical(test_labels, num_classes=3)

In [89]:
train_labels[0]

array([0., 1., 0.], dtype=float32)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
from sklearn.preprocessing import Normalizer
transformer = Normalizer()
train_set = transformer.fit_transform(train_set)

In [0]:
model = tf.keras.models.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
model.add(tf.keras.layers.Dense(3, input_shape=(4,),activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', 
              metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [103]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [106]:
model.fit(train_set,train_labels,          
          validation_data=(test_set,test_labels),
          epochs=100)

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 0s 273us/sample - loss: 1.0233 - accuracy: 0.6964 - val_loss: 1.1310 - val_accuracy: 0.5000
Epoch 2/100
112/112 [==============================] - 0s 216us/sample - loss: 1.0228 - accuracy: 0.6964 - val_loss: 1.1267 - val_accuracy: 0.5000
Epoch 3/100
112/112 [==============================] - 0s 256us/sample - loss: 1.0223 - accuracy: 0.6964 - val_loss: 1.1258 - val_accuracy: 0.5000
Epoch 4/100
112/112 [==============================] - 0s 188us/sample - loss: 1.0218 - accuracy: 0.6964 - val_loss: 1.1228 - val_accuracy: 0.5000
Epoch 5/100
112/112 [==============================] - 0s 209us/sample - loss: 1.0215 - accuracy: 0.6964 - val_loss: 1.1184 - val_accuracy: 0.5000
Epoch 6/100
112/112 [==============================] - 0s 210us/sample - loss: 1.0209 - accuracy: 0.6964 - val_loss: 1.1122 - val_accuracy: 0.4737
Epoch 7/100
112/112 [==============================] - 0s 208us/sample - 

## Question 10

### Make predictions
- Predict labels on one row

In [107]:
model.input

<tf.Tensor 'dense_5_input:0' shape=(None, 4) dtype=float32>

In [112]:
input_data = np.expand_dims(test_set[0], axis=0)
print(input_data.shape)


(1, 4)


In [113]:
pred = model.predict(input_data)
pred

array([[0.08158981, 0.49483126, 0.42357898]], dtype=float32)

In [114]:
pred[0]

array([0.08158981, 0.49483126, 0.42357898], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [120]:
test_labels[0]

array([0., 0., 1.], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [0]:
import tensorflow as tf
print(tf.__version__)

### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [0]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

In [122]:
import os
from google.colab import drive
drive.mount('/content/gdrive')

os.chdir('/content/gdrive/My Drive/Neural Network')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
import pandas as pd
price = pd.read_csv("prices.csv")

In [203]:
price.head(5)

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [204]:
price = price.drop(columns=['date','symbol'])
price.head(5)

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [205]:
price.shape

(851264, 5)

In [0]:
price1 = price.head(1000)

In [207]:
price1.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
array = price1.values
X = array[:,0:4] 
y = array[:,4]   

In [0]:
y = y/1000000

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
X = np.array(X)

In [0]:
y = np.array(y)

In [0]:
X = X.astype('float32')
y = y.astype('float32')

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [213]:
tf.math.l2_normalize(
    X,
    axis=None,
    epsilon=1e-12,
    name=None
)

<tf.Tensor: id=56697, shape=(1000, 4), dtype=float32, numpy=
array([[0.02202894, 0.02245906, 0.02182905, 0.02253223],
       [0.02235197, 0.02141321, 0.02140607, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051192, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.0079956 , 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

In [0]:
from sklearn.model_selection import train_test_split
train_set, test_set, train_labels, test_labels = train_test_split(X, y, test_size=0.25, random_state=0)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
import tensorflow as tf
tf.__version__
w = tf.zeros(shape=(4,1))
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
def prediction(x, w, b):
    
    xw_matmul = tf.matmul(x, w)
    y = tf.add(xw_matmul, b)
    
    return y

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
def loss(y_actual, y_predicted):
    
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    
    return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    #Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
        t.watch([w,b])
        
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    #Update Weights and Bias
    w = w - learning_rate*dw
    b = b - learning_rate*db
    
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [219]:
for i in range(100):
    
    w, b = train(train_set, train_labels, w, b)
    print('Current Loss on iteration', i, loss(train_labels, prediction(train_set, w, b)).numpy())

Current Loss on iteration 0 6535296.0
Current Loss on iteration 1 3123993000000.0
Current Loss on iteration 2 1.4933751e+18
Current Loss on iteration 3 7.1388294e+23
Current Loss on iteration 4 3.4125996e+29
Current Loss on iteration 5 inf
Current Loss on iteration 6 inf
Current Loss on iteration 7 inf
Current Loss on iteration 8 inf
Current Loss on iteration 9 inf
Current Loss on iteration 10 inf
Current Loss on iteration 11 inf
Current Loss on iteration 12 inf
Current Loss on iteration 13 inf
Current Loss on iteration 14 nan
Current Loss on iteration 15 nan
Current Loss on iteration 16 nan
Current Loss on iteration 17 nan
Current Loss on iteration 18 nan
Current Loss on iteration 19 nan
Current Loss on iteration 20 nan
Current Loss on iteration 21 nan
Current Loss on iteration 22 nan
Current Loss on iteration 23 nan
Current Loss on iteration 24 nan
Current Loss on iteration 25 nan
Current Loss on iteration 26 nan
Current Loss on iteration 27 nan
Current Loss on iteration 28 nan
Curre

### Observe values of Weight
- Print the updated values

In [200]:
print('Weights:\n', w.numpy())

Weights:
 [[nan]
 [nan]
 [nan]
 [nan]]


### Observe values of Bias
- Print the updated values

In [201]:
print('Bias:\n',b.numpy())

Bias:
 [nan]
